// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdhYVVmDadv90QemGAWfH6u5kYngKrdhw',
    appId: '1:552055356200:web:82a70f5e0b8a23c450ae1d',
    messagingSenderId: '552055356200',
    projectId: 'note-app-585e4',
    authDomain: 'note-app-585e4.firebaseapp.com',
    storageBucket: 'note-app-585e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9TJAKgRQR4iMMXSt1AeiIr-18Ig_9N8',
    appId: '1:552055356200:android:af45ce66851d3d2450ae1d',
    messagingSenderId: '552055356200',
    projectId: 'note-app-585e4',
    storageBucket: 'note-app-585e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fg1aBZ8YFnV6eiHaUh1elEnKEO80WHQ',
    appId: '1:552055356200:ios:deb1ff023947732b50ae1d',
    messagingSenderId: '552055356200',
    projectId: 'note-app-585e4',
    storageBucket: 'note-app-585e4.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6fg1aBZ8YFnV6eiHaUh1elEnKEO80WHQ',
    appId: '1:552055356200:ios:bba24cc94438dcd250ae1d',
    messagingSenderId: '552055356200',
    projectId: 'note-app-585e4',
    storageBucket: 'note-app-585e4.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
